# Generated by Django 4.2.6 on 2023-12-11 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_singin_updb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singin_updb',
            name='Email',
        ),
    ]
