# Generated by Django 4.2.6 on 2023-12-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_singinupdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singinupdb',
            name='Email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
