# Generated by Django 4.2.6 on 2023-12-11 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_alter_singinupdb_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='singin_updb',
            new_name='singin_indb',
        ),
    ]
