# Generated by Django 4.2.6 on 2023-12-12 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_rename_singin_updb_singin_indb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='singin_indb',
        ),
    ]
