# Generated by Django 4.2.6 on 2024-01-01 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_rename_username_cartdb_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartdb',
            old_name='product_name',
            new_name='product_Name',
        ),
    ]
