# Generated by Django 4.2.6 on 2024-01-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_rename_product_name_cartdb_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdb',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
