# Generated by Django 4.2.6 on 2023-11-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fooddb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Email', models.EmailField(blank=True, max_length=20, null=True)),
                ('Place', models.CharField(blank=True, max_length=50, null=True)),
                ('Mobile', models.IntegerField(blank=True, null=True)),
                ('Profile', models.ImageField(blank=True, null=True, upload_to='img')),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
