# Generated by Django 4.2.6 on 2023-11-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooddb',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='fooddb',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='fooddb',
            name='Mobile',
        ),
        migrations.RemoveField(
            model_name='fooddb',
            name='Place',
        ),
        migrations.AddField(
            model_name='fooddb',
            name='Description',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
