# Generated by Django 4.2.6 on 2023-12-04 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_catdb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='catdb',
            new_name='prodb',
        ),
    ]
